<nav>
  <ul id="menu">
    <!--#if expr="v('DOCUMENT_NAME') == 'home.html'" -->
    <li>
      <a href="#">Home</a>
    </li>
    <!--#else -->
    <li>
      <a href="/students/yliang58/home.html">Home</a>
    </li>
    <!--#endif -->
    <li>
      <a href="#">About This Course</a>
    </li>
    <li>
      <a href="#" class="drop">Lectures</a>
      <div class="dropdown_3columns">
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Lecture 1</a>
            </li>
            <li>
              <a href="#">Lecture 2</a>
            </li>
            <!--#if expr="v('DOCUMENT_NAME') == 'lecture3.html'" -->
            <li>
              <a href="#">Lecture 3</a>
            </li>
            <!--#else -->
            <li>
              <a href="/students/yliang58/lectures/lecture3.html">Lecture 3</a>
            </li>
            <!--#endif -->
            <li>
              <a href="#">Lecture 4</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Lecture 5</a>
            </li>
            <li>
              <a href="#">Lecture 6</a>
            </li>
            <li>
              <a href="#">Lecture 7</a>
            </li>
            <li>
              <a href="#">Lecture 8</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Lecture 9</a>
            </li>
            <li>
              <a href="#">Lecture 10</a>
            </li>
            <li>
              <a href="#">Lecture 11</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li>
      <a href="#" class="drop">Exercises/Solutions</a>
      <div class="dropdown_3columns">
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Exercises/Solutions 1</a>
            </li>
            <li>
              <a href="#">Exercises/Solutions 2</a>
            </li>
            <li>
              <a href="#">Exercises/Solutions 3</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Exercises/Solutions 4</a>
            </li>
            <li>
              <a href="#">Exercises/Solutions 5</a>
            </li>
            <li>
              <a href="#">Exercises/Solutions 6</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Exercises/Solutions 7</a>
            </li>
            <!--#if expr="v('DOCUMENT_NAME') == 'exercise8.html'" -->
            <li>
              <a href="#">Exercises/Solutions 8</a>
            </li>
            <!--#else -->
            <li>
              <a href="/students/yliang58/exercises/exercise8.html">Exercises/Solutions 8</a>
            </li>
            <!--#endif -->
            <li>
              <a href="#">Exercises/Solutions 9</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li>
      <a href="#" class="drop">Homework</a>
      <div class="dropdown_3columns">
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Homework 1</a>
            </li>
            <li>
              <a href="#">Homework 2</a>
            </li>
            <li>
              <a href="#">Homework 3</a>
            </li>
            <li>
              <a href="#">Homework 4</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Homework 5</a>
            </li>
            <li>
              <a href="#">Homework 6</a>
            </li>
            <li>
              <a href="#">Homework 7</a>
            </li>
            <li>
              <a href="#">Homework 8</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Homework 9</a>
            </li>
            <li>
              <a href="#">Final Project</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li>
      <a href="#" class="drop">Quizzes</a>
      <div class="dropdown_3columns">
        <div class="col_1">
          <ul>
            <!--#if expr="v('DOCUMENT_NAME') == 'quiz1.html'" -->
            <li>
              <a href="#">Quiz 1</a>
            </li>
            <!--#else -->
            <li>
              <a href="/students/yliang58/quizzes/quiz1.html">Quiz 1</a>
            </li>
            <!--#endif -->
            <li>
              <a href="#">Quiz 2</a>
            </li>
            <li>
              <a href="#">Quiz 3</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Quiz 4</a>
            </li>
            <li>
              <a href="#">Quiz 5</a>
            </li>
            <li>
              <a href="#">Quiz 6</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="#">Quiz 7</a>
            </li>
            <li>
              <a href="#">Quiz 8</a>
            </li>
            <li>
              <a href="#">Final Exam</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <!--#if expr="v('DOCUMENT_NAME') == 'resources.html'" -->
    <li>
      <a href="#">Resources</a>
    </li>
    <!--#else -->
    <li>
      <a href="/students/yliang58/resources.html">Resources</a>
    </li>
    <!--#endif -->
            
    <li class="menu_right">
      <a href="https://my.bcit.ca/cp/home/displaylogin">my.bcit.ca</a>
    </li>
  </ul>
</nav>