     <img id="nav_icon" src="/students/yliang58/images/menu_icon_1.png" alt="mobile view's menu icon"/>
	<div id="nav">
	<!--a menu for thinscreen client starts from here -->
	
		<ul id="navlist">
		<!--"navlist"starts from here-->
			<li><a href="#">About COMP1950</a></li>
			<li id="lecture"><a href="#">Lectures</a>
          <ul id="lecture_list">
          <!--a submenu for lectures starts-->
            <li>
              <a href="#">Lecture 1</a>
            </li>
            <li>
              <a href="#">Lecture 2</a>
            </li>
            <!--#if expr="v('DOCUMENT_NAME') == 'lecture3.html'" -->
            <li>
              <a href="#">Lecture 3</a>
            </li>
            <!--#else -->
            <li>
              <a href="/students/yliang58/lectures/lecture3.html">Lecture 3</a>
            </li>
            <!--#endif -->
            <li>
              <a href="#">Lecture 4</a>
            </li>
            <li>
              <a href="#">Lecture 5</a>
            </li>
            <li>
              <a href="#">Lecture 6</a>
            </li>
            <li>
              <a href="#">Lecture 7</a>
            </li>
            <li>
              <a href="#">Lecture 8</a>
            </li>
             <!--a submenu for lectures ends-->
             </ul>
            </li>
            
            
			<li id="exercise"><a href="#">Exercises/Solutions</a>
			 <ul id="exercise_list">
			       <!--a submenu for exercises/solutions starts-->
         <li>
           <a href="#">Exercises/Solutions 1</a>
         </li>
         <li>
           <a href="#">Exercises/Solutions 2</a>
         </li>
         <li>
           <a href="#">Exercises/Solutions 3</a>
         </li>
         <li>
           <a href="#">Exercises/Solutions 4</a>
         </li>
         <li>
           <a href="#">Exercises/Solutions 5</a>
         </li>
         <li>
           <a href="#">Exercises/Solutions 6</a>
         </li>
         <li>
           <a href="#">Exercises/Solutions 7</a>
         </li>
         <!--#if expr="v('DOCUMENT_NAME') == 'exercise8.html'" -->
         <li>
           <a href="#">Exercises/Solutions 8</a>
         </li>
         <!--#else -->
         <li>
           <a href="/students/yliang58/exercises/exercise8.html">Exercises/Solutions 8</a>
         </li>
         <!--#endif -->
         <li>
           <a href="#">Exercises/Solutions 9</a>
         </li>
            
        	<!--a submenu for exercises/solutions ends-->
          	</ul>
		 	 </li>
		<li id="homework"><a href="#">Homework</a>
			<ul id="homework_list">
			 <!--a submenu for homework starts-->
        <li>
          <a href="#">Homework 1</a>
        </li>
        <li>
          <a href="#">Homework 2</a>
        </li>
        <li>
          <a href="#">Homework 3</a>
        </li>
        <li>
          <a href="#">Homework 4</a>
        </li>

        <li>
          <a href="#">Homework 5</a>
        </li>
        <li>
          <a href="#">Homework 6</a>
        </li>
        <li>
          <a href="#">Homework 7</a>
        </li>
        <li>
          <a href="#">Homework 8</a>
        </li>

        <li>
          <a href="#">Homework 9</a>
        </li>
        <li>
          <a href="#">Final Project</a>
        </li>
             <!--a submenu for homework ends-->  
            </ul>
            </li>
			<li id="quiz"><a href="#">Quizzes</a>
			<!--a submenu for homework starts-->  
          <ul id="quiz_list">
            <!--#if expr="v('DOCUMENT_NAME') == 'quiz1.html'" -->
            <li>
              <a href="#">Quiz 1</a>
            </li>
            <!--#else -->
            <li>
              <a href="/students/yliang58/quizzes/quiz1.html">Quiz 1</a>
            </li>
            <!--#endif -->
            <li>
              <a href="#">Quiz 2</a>
            </li>
            <li>
              <a href="#">Quiz 3</a>
            </li>
            <li>
              <a href="#">Quiz 4</a>
            </li>
            <li>
              <a href="#">Quiz 5</a>
            </li>
            <li>
              <a href="#">Quiz 6</a>
            </li>
            <li>
              <a href="#">Quiz 7</a>
            </li>
            <li>
              <a href="#">Quiz 8</a>
            </li>
            <li>
              <a href="#">Final Exam</a>
            </li>
            </ul>  
            <!--a submenu for quizzes ends from here -->
			</li>

      <li>
        <a href="/students/yliang58/resources.html">Resources</a>
      </li>
      		<li><a href="https://my.bcit.ca/cp/home/displaylogin">my.bcit.ca</a>
      		</li>
		</ul>
		<!--"navlist"ends from here-->
	<!--a menu for thinscreen client starts from here  -->
	</div>
   